[package]
name = 'games'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
[dependencies]
ggwpcoin = { local = "../ggwp_coin" }
ggwp_core = { local = "../core" }
[addresses]
games = "0x3dd2eb713a9f50bf722ccbd9deaee12f8faaf45b40636585b47ecb8dd888104a"
