[package]
name = 'ggwp_core'
version = '1.0.0'
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'
[dependencies]
ggwpcoin = { local = "../ggwp_coin" }
[addresses]
ggwp_core = "0xb048c923618b91bf4498985ce826f7c7319a1ffebdfb4c49ef240f78c051f24d"
